$(document).ready(function(){
    // På förstasidan: Skapar en h1 till diven som ligger ovanpå carusell och statisk header
    let h1HeaderDiv = $("<h1>").html("Say it with flowers").appendTo($("#carusellDiv"));
    $(h1HeaderDiv).addClass("carusel_h1");

    // På förstasidan: Skapa p-tagg och lägger till den i #carusellDiv
    let pHeaderDiv = $("<p>").html("Beautiful and fresh flowers made daily and delivered across Sweden.").appendTo("#carusellDiv");
    $(pHeaderDiv).addClass("carusel_p");    
    
    let flowers = [
        {id: '1', title: 'Sweet heart', price: 599, articlenr: 936746, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/birthday_flowers/birthdayflowers1.jpg", category: "Birthdayflowers" },
        {id: '2', title: 'Shining star', price: 699, articlenr: 984263, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/birthday_flowers/birthdayflowers2.jpg", category: "Birthdayflowers" },
        {id: '3', title: 'Only prettier', price: 799, articlenr: 548352, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/birthday_flowers/birthdayflowers3.jpg", category: "Birthdayflowers" },
        {id: '4', title: 'Miracle', price: 899, articlenr: 857253, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/birthday_flowers/birthdayflowers4.jpg", category: "Birthdayflowers" },
        {id: '5', title: 'Joyful pleasure', price: 540, articlenr: 548392, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/birthday_flowers/birthdayflowers5.jpg", category: "Birthdayflowers" },

        {id: '6', title: 'Endless love', price: 599, articlenr: 458392, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/love_flowers/loveflowers1.jpg", category: "Loveflowers" },
        {id: '7', title: 'True romance', price: 699, articlenr: 539237, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/love_flowers/loveflowers2.jpg", category: "Loveflowers" },
        {id: '8', title: 'Amore', price: 799, articlenr: 290582, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/love_flowers/loveflowers3.jpg", category: "Loveflowers" },
        {id: '9', title: 'Deep breaths', price: 899, articlenr: 109364, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/love_flowers/loveflowers4.jpg", category: "Loveflowers" },
        {id: '10', title: 'Blossom fairy', price: 540, articlenr: 204678, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/love_flowers/loveflowers5.jpg", category: "Loveflowers" },

        {id: '11', title: 'Song bird', price: 599, articlenr: 206473, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/holiday_flowers/holidayflowers1.jpg", category: "Holidayflowers" },
        {id: '12', title: 'Wonderful day', price: 699, articlenr: 947382, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/holiday_flowers/holidayflowers2.jpg", category: "Holidayflowers" },
        {id: '13', title: 'Purity', price: 799, articlenr: 302765, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/holiday_flowers/holidayflowers3.jpg", category: "Holidayflowers" },
        {id: '14', title: 'Glamorous', price: 899, articlenr: 193648, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/holiday_flowers/holidayflowers4.jpg", category: "Holidayflowers" },
        {id: '15', title: 'Fantasy', price: 540, articlenr: 374892, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/holiday_flowers/holidayflowers5.jpg", category: "Holidayflowers" },

        {id: '16', title: 'Grace', price: 599, articlenr: 947362, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/season_flowers/seasonflowers1.jpg", category: "Seasonflowers" },
        {id: '17', title: 'Daydream', price: 699, articlenr: 129376, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/season_flowers/seasonflowers2.jpg", category: "Seasonflowers" },
        {id: '18', title: 'Wild garden', price: 799, articlenr: 431932, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/season_flowers/seasonflowers3.jpg", category: "Seasonflowers" },
        {id: '19', title: 'Summerday', price: 899, articlenr: 763592, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/season_flowers/seasonflowers4.jpg", category: "Seasonflowers" },
        {id: '20', title: 'Sparkle forest', price: 540, articlenr: 267839, description: 'All of our flower products are individually crafted from the best blossoms daily. If any flower shown is unavailable for any reason, we may make a substitution of equal or greater value in similar color to ensure timely delivery.', img: "../img/products_img/season_flowers/seasonflowers5.jpg", category: "Seasonflowers" },

    ];

    localStorage.setItem("Flowers", JSON.stringify(flowers));
});